#!/usr/bin/env bash

set -e

pushd "$(realpath "$(dirname "$0")")"

CURR_DIR="${PWD}"

BUILD_TYPE="$1"
if [ -z "$BUILD_TYPE" ]; then
	BUILD_TYPE=Release
fi

mkdir -p build/wasm
if [ ! -d build/emsdk ]; then
	git clone https://github.com/emscripten-core/emsdk.git build/emsdk
fi

pushd build/emsdk
#git pull
./emsdk install latest
./emsdk activate latest
source ./emsdk_env.sh
popd # build/emsdk

pushd build/wasm
emcmake cmake -DCMAKE_BUILD_TYPE="$BUILD_TYPE" -DBUILD_WASM=ON ../..
make -j

TARGET_FILES="
	TomlLegacy.js
	TomlWasm.js
	TomlWasm.wasm
	TomlWasmBundle.js
	${CURR_DIR}/LICENSE.txt
"

cp $TARGET_FILES "${CURR_DIR}/node/out/"
popd

popd
